//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentChallenge.Data.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevelopmentChallenge.Data.Infrastructure.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área.
        /// </summary>
        internal static string Área {
            get {
                return ResourceManager.GetString("Área", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculo.
        /// </summary>
        internal static string Círculo {
            get {
                return ResourceManager.GetString("Círculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Círculos.
        /// </summary>
        internal static string Círculo_Plural {
            get {
                return ResourceManager.GetString("Círculo_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrado.
        /// </summary>
        internal static string Cuadrado {
            get {
                return ResourceManager.GetString("Cuadrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuadrados.
        /// </summary>
        internal static string Cuadrado_Plural {
            get {
                return ResourceManager.GetString("Cuadrado_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formas.
        /// </summary>
        internal static string Formas {
            get {
                return ResourceManager.GetString("Formas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perímetro.
        /// </summary>
        internal static string Perimetro {
            get {
                return ResourceManager.GetString("Perimetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectángulo.
        /// </summary>
        internal static string Rectangulo {
            get {
                return ResourceManager.GetString("Rectangulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectángulos.
        /// </summary>
        internal static string Rectangulo_Plural {
            get {
                return ResourceManager.GetString("Rectangulo_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporte de Formas.
        /// </summary>
        internal static string Reporte {
            get {
                return ResourceManager.GetString("Reporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecio.
        /// </summary>
        internal static string Trapecio {
            get {
                return ResourceManager.GetString("Trapecio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trapecios.
        /// </summary>
        internal static string Trapecio_Plural {
            get {
                return ResourceManager.GetString("Trapecio_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulo.
        /// </summary>
        internal static string Triángulo {
            get {
                return ResourceManager.GetString("Triángulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triángulos.
        /// </summary>
        internal static string Triángulo_Plural {
            get {
                return ResourceManager.GetString("Triángulo_Plural", resourceCulture);
            }
        }
    }
}
